apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: snmxu9i0f-python 
  janus-idp.io/tekton: snmxu9i0f-python
  backstage.io/kubernetes-id: snmxu9i0f-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: snmxu9i0f-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  